[custom_args]
hf_weight_transform = "replicate"

[moe_overrides]
load_balance_coeff = 0.0
hf_ffn_hidden_dim = 8192
route_norm = true
top_k = 2
route_scale = 1
num_shared_experts = 0

[model_overrides]
custom_moe_impl = "virtual_group"
moe_inter_dim = 8192

[top_k_args]
name = "no_op"

[job]
dump_folder = "./outputs"
description = "Llama-3-MoE debug model"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama3_moe"
flavor = "3B"
hf_assets_path = "/gpfs/goon/models/Llama-3.2-3B-no-tied-weights"

[optimizer]
name = "AdamW"
lr = 1e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 10  # lr scheduler warm up

[training]
local_batch_size = 1
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 100
dataset = "c4_test"  # for full training use "c4"
enable_cpu_offload = false

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
pipeline_parallel_schedule = "Interleaved1F1B"
expert_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 9999999999999999999
last_save_model_only = false # Set to false so we can test continued training.
export_dtype = "bfloat16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]


[compile]
enable=false
components = ["model", "loss"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output", "router.gate"]

[validation]
enable = false
dataset = "c4_validation"
freq = 500
steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192
