# We define a custom JobConfig class with an addition catch-all custom_args field
[experimental]
custom_args_module = "torchtitan.models.llama3_moe.custom_args"

[job]
dump_folder = "./outputs"
description = "Llama 3 MoE training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama3_moe"
flavor = "3B_8exp"
hf_assets_path = "./assets/hf/Llama-3.2-3B-no-tied-weights"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 1e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 10  # lr scheduler warm up

[training]
local_batch_size = 1
seq_len = 2048  # 8192
max_norm = 1.0  # grad norm clipping
steps = 100
dataset = "c4_test"  # for full training use "c4"
enable_cpu_offload = false

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
pipeline_parallel_schedule = "Interleaved1F1B"
expert_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
load_only = true  # for debugging, never save trained ckpts
folder = "checkpoint"  # takes precedence for load & save
interval = 500
last_save_model_only = true
export_dtype = "bfloat16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
exclude_from_loading = [""]
initial_load_model_only = true  # required to load HF ckpt (only loads params, not optimizer)
initial_load_in_hf = true

[compile]
enable=false
components = ["model", "loss"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output", "router.gate"]

[validation]
enable = false
dataset = "c4_validation"
freq = 500
steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192
